type imap_account = {
  host : string;
  port : int;
  user : string;
  password : string;
  use_tls : bool;
}

type t = {
  account : imap_account;
  maildir_path : string;
  channel_name : string;
}

let generate config =
  let maildir_path =
    if Filename.is_relative config.maildir_path then
      Filename.concat (Sys.getcwd ()) config.maildir_path
    else
      config.maildir_path
  in
  let tls_line = if config.account.use_tls then
    "TLSType IMAPS"
  else
    "TLSType None"
  in
  Printf.sprintf
{|# Generated by sakura-mail — do not edit manually

IMAPAccount %s
Host %s
Port %d
User %s
Pass %s
%s
AuthMechs LOGIN

IMAPStore %s-remote
Account %s

MaildirStore %s-local
SubFolders Verbatim
Path %s/
Inbox %s/INBOX

Channel %s
Far :%s-remote:
Near :%s-local:
Patterns *
Create Both
Remove Both
Expunge Both
SyncState *
|}
    config.channel_name
    config.account.host
    config.account.port
    config.account.user
    config.account.password
    tls_line
    config.channel_name config.channel_name
    config.channel_name
    maildir_path maildir_path
    config.channel_name
    config.channel_name config.channel_name

let write_config ~path config =
  let content = generate config in
  let oc = open_out path in
  output_string oc content;
  close_out oc
